spring:
  profiles:
    active: node1

# 全局配置
settings:
  # 是否启用节点发现，鉴于网上很多同学都吐槽说项目启动的时候一直不断的抛出异常，其实这是系统启动之后自动同步其他节点的最新区块数据导致的
  # 因为 tio 配置的初始同步节点都没有启动，所以一直抛出连接超时的异常，其实这并不影响系统运行，
  # 但是为了方便那些有强迫症的同学（本人也是强迫症患者），在这里增加这配置，默认部署成单节点，不同步数据。
  node-discover: false
  # 发生交易时是否自动挖矿
  auto-mining: true

# 关闭 tio 日志
logging:
  level:
    org:
      tio:
        server: OFF
        client: OFF
